name: Aqua

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Aqua.jl
        run: |
          julia --color=yes -e 'using Pkg; Pkg.add("Aqua"); Pkg.develop(path="."); using Aqua, MultiPrecisionR2; Aqua.test_all(MultiPrecisionR2, ambiguities=false); Aqua.test_ambiguities(MultiPrecisionR2
        )'
